# Generated by Django 5.0.2 on 2024-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('pice', models.IntegerField()),
                ('is_special', models.BooleanField(null=True)),
                ('promotion_end_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
